site_name: Localization Simulator

theme: 
  name: 'material'
  palette:
    primary: indigo
    accent: green

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [localization_simulator]


nav:
  - core:
    - main: main.md
    - component: component.md
    - error: error.md
    - map: map.md
    - plot: plot.md
  - utils:
    - helper: helper.md
    - Newton Solver: nls.md
    - trajectory: trajectory.md