name: "Test"
map: [20,20]
k: 2
anchor:
  - name: "a"
    location: [2,0]
    cutoff: 0
    error: [0,3]
    colour: "red"
  - name: "b"
    location: [3,0]
    cutoff: 0
    error: [0,3]
    colour: "blue"
  - name: "c"
    location: [1,2]
    cutoff: 0
    error: [0,3]
    colour: "red"
  - name: "d"
    location: [100,100]
    cutoff: 0
    error: [0,3]
    colour: "red"
pose: [[1,0]]
isotropic: 100
sensor_measurement_variance: 1
hessian: False
