name: "Test"
map: [20,20]
k: 2
anchor:
  - name: "a"
    location: [8,5]
    cutoff: 0
    error: [0,3]
    colour: "red"
  - name: "b"
    location: [6,8]
    cutoff: 0
    error: [0,3]
    colour: "blue"
  - name: "c"
    location: [6,14]
    cutoff: 0
    error: [0,3]
    colour: "red"
pose: [[5,5],[7,7]]
isotropic: 1
sensor_measurement_variance: 1
hessian: False
